//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spotify.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Song
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Song()
        {
            this.Albums = new HashSet<Album>();
            this.Playlists = new HashSet<Playlist>();
        }
        
        public static void InitUri(ref Song song)
        {
            song.SongLinkUri = new Uri(song.SongLink == null ? "" : song.SongLink, UriKind.RelativeOrAbsolute);
            song.SongImageUri = new Uri(song.SongImage == null ? "" : song.SongImage, UriKind.RelativeOrAbsolute);
        }

        public int ID { get; set; }
        public string SongName { get; set; }
        public string SongLink { get; set; }
        public string SingerName { get; set; }
        public string SongImage { get; set; }
        public string AlbumName { get; set; }
        public string Descriptions { get; set; }
        public string PostTime { get; set; }
        public string SongDuration { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Album> Albums { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Playlist> Playlists { get; set; }
        public Uri SongLinkUri { get; set; }
        public Uri SongImageUri { get; set; }
    }
}
